# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Snowpack App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      
    - name: Launch the local action
    - uses: ./ # Uses an action in the root directory
      id: badge
      with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
          ignore: 'node_modules/|README'

    - name: Deploy to image-data branch
    - uses: peaceiris/actions-gh-pages@v3
      
      with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
